/**
 * @typedef Notification
 * @property {string} id - The id of the notification.
 * @property {string} type - The type of the notification.
 * @property {number} lastTriggered - The last time the notification was triggered.
 * @property {number} displayTimeSec - The time the notification should be displayed in seconds.
 * @property {number} miniTimeSec - The time the notification should be minimized in seconds.
 * @property {boolean} closeable - If the notification can be closed.
 * @property {boolean} miniable - If the notification can be minimized.
 * @property {string} title - The title of the notification.
 * @property {string} comment - The comment of the notification.
 * @property {number} camId - The id of the camera.
 * @property {Array<any>} actions - The actions of the notification.
 */

/**
 * @typedef State
 * @type {Object.<string, (Notification | any)>}
 * @this {{[k: string]: (Notification | any)}} state
 * @property {Notification} notifyDictRotation0
 * @property {Notification} notifyDictRotation1
 * @property {Notification} notifyRecNoSettings
 */

/**
 * @type State
 */
const state = {
	notifyDictRotation0: {
		id: 'dictRotation0',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'maintenanceMode',
		comment: 'maintenanceModeInfo',
		camId: 0,
		actions: []
	},
	notifyDictRotation1: {
		id: 'dictRotation1',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'maintenanceMode',
		comment: 'maintenanceModeInfo',
		camId: 1,
		actions: []
	},
	notifyRecNoSettings: {
		id: 'recNoSettings',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 10,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'cantSetWhileRecordingHeader',
		comment: 'cantSetWhileRecordingComment'
	},
	notifyRecBackupNoSettings: {
		id: 'recBackupNoSettings',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 10,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'cantChangeSettingsWhileRecordingBackupHeader',
		comment: 'cantChangeSettingsWhileRecordingBackupComment'
	},
	notifyRecError: {
		id: 'recError',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 20,
		miniTimeSec: 0,
		closeable: true,
		miniable: true,
		title: 'recordingErrorHeader',
		comment: 'recordingErrorComment'
	},
	notifyStorageDetected: {
		id: 'storageDetected',
		type: 'info',
		lastTriggered: 1710840075,
		displayTimeSec: 20,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'storageDetectedTitle',
		comment: 'storageDetectedComment',
		actions: [
			{
				text: 'USB2',
				key: 'backupStorage',
				value: '/mnt/wsl/docker-desktop/cli-tools',
				confirmationNeeded: false,
				confirmationTranslation: '',
				actionOnClose: false
			}
		]
	},
	notifyCifsConnectionError: {
		id: 'cifsConnectionError',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'cifsConnectionError',
		comment: '<cifsError>',
		cifsError: ''
	},
	notifyPressureToHigh0: {
		id: 'pressureToHigh0',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'pressureToHigh',
		comment: 'reducePressure',
		camId: 0,
		setpoint: '1150mbar',
		currentValue: '<psi0>'
	},
	notifyPressureToHigh1: {
		id: 'pressureToHigh1',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'pressureToHigh',
		comment: 'reducePressure',
		camId: 1,
		setpoint: '1150mbar',
		currentValue: '<psi1>'
	},
	notifyPressureToLow0: {
		id: 'pressureToLow0',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'pressureToLow',
		comment: 'raisePressure',
		camId: 0,
		setpoint: '1150mbar',
		currentValue: '<psi0>'
	},
	notifyPressureToLow1: {
		id: 'pressureToLow1',
		type: 'critical',
		lastTriggered: 1710840074,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'pressureToLow',
		comment: 'raisePressure',
		camId: 1,
		setpoint: '1150mbar',
		currentValue: '<psi1>'
	},
	notifyNewerLocalFirmwareUpdateWithTimer: {
		id: 'newerLocalFirmwareUpdateWithTimer',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'newerLocalFirmwareHeader',
		comment: 'newerLocalFirmwareCommentWithTimer',
		actions: []
	},
	notifyNewerLocalFirmwareUpdate: {
		id: 'newerLocalFirmwareUpdate',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'newerLocalFirmwareHeader',
		comment: 'newerLocalFirmwareComment',
		actions: []
	},
	notifyOnlineFirmwareUpdate: {
		id: 'onlineFirmwareUpdate',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'onlineUpdateHeader',
		comment: 'onlineUpdateComment',
		tooltip: [],
		actions: []
	},
	notifyOnlineSoftwareConfig: {
		id: 'onlineSoftwareConfig',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'onlineUpdateConfigHeader',
		comment: 'onlineUpdateConfigComment'
	},
	notifyWarningDiskmonFreespace: {
		id: 'warningDiskmonFreespace',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'warningDiskmonFreespaceTitle',
		comment: 'warningDiskmonFreespace'
	},
	notifyErrorStoreaviDrop: {
		id: 'errorStoreaviDrop',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorStoreaviDropTitle',
		comment: 'errorStoreaviDrop'
	},
	notifyErrorStoreaviRelease: {
		id: 'errorStoreaviRelease',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorStoreaviReleaseTitle',
		comment: 'errorStoreaviRelease'
	},
	notifyErrorStoreSpeed: {
		id: 'errorStoreSpeed',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorStoreSpeedTitle',
		comment: 'errorStoreSpeed'
	},
	notifyErrorJpgstoreSpeed: {
		id: 'errorJpgstoreSpeed',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorJpgstoreSpeedTitle',
		comment: 'errorJpgstoreSpeed'
	},
	notifyErrorJpgstoreDiskspace: {
		id: 'errorJpgstoreDiskspace',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 10,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorJpgstoreDiskspaceTitle',
		comment: 'errorJpgstoreDiskspace'
	},
	notifyErrorJpgstoreIo: {
		id: 'errorJpgstoreIo',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorJpgstoreIoTitle',
		comment: 'errorJpgstoreIo'
	},
	notifyErrorJpgnetstoreIo: {
		id: 'errorJpgnetstoreIo',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorJpgnetstoreIoTitle',
		comment: 'errorJpgnetstoreIo'
	},
	notifyErrorSnapPath: {
		id: 'errorSnapPath',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorSnapPathTitle',
		comment: 'errorSnapPath'
	},
	notifyErrorStartInitFAILED: {
		id: 'errorStartInitFAILED',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorStartInitFAILEDTitle',
		comment: 'errorStartInitFAILED'
	},
	notifyErrorStopFinalizeFAILED: {
		id: 'errorStopFinalizeFAILED',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorStopFinalizeFAILEDTitle',
		comment: 'errorStopFinalizeFAILED'
	},
	notifyErrorNewpathPath: {
		id: 'errorNewpathPath',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorNewpathPathTitle',
		comment: 'errorNewpathPath'
	},
	notifyWarningNetworkUniqueIP: {
		id: 'warningNetworkUniqueIP',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'warningNetworkUniqueIPTitle',
		comment: 'warningNetworkUniqueIPComment'
	},
	notifyWarningPortUsed: {
		id: 'warningPortUsed',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'warningPortUsedTitle',
		comment: 'warningPortUsedComment',
		portValue: 0,
		fallbackPort: 0
	},
	notifyErrorInvalidCertificate: {
		id: 'errorInvalidCertificate',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'errorInvalidCertificateTitle',
		comment: 'errorInvalidCertificateComment',
		systemMessage: ''
	},
	notifyWarningNoServerRunning: {
		id: 'warningNoServerRunning',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'warningNoServerRunningTitle',
		comment: 'warningNoServerRunningComment'
	},
	notifyNoBackupCapacity: {
		id: 'noBackupCapacity',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'noBackupCapacityTitle',
		comment: 'noBackupCapacityComment'
	},
	notifyWarningRotation0: {
		id: 'warningRotation0',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'warningRotationTitle',
		comment: 'warningRotationComment',
		camId: 0
	},
	notifyWarningRotation1: {
		id: 'warningRotation1',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'warningRotationTitle',
		comment: 'warningRotationComment',
		camId: 1
	},
	notifyErrorRotation0: {
		id: 'errorRotation0',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorRotationTitle',
		comment: 'errorRotationComment',
		camId: 0
	},
	notifyErrorRotation1: {
		id: 'errorRotation1',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 10,
		closeable: true,
		miniable: true,
		title: 'errorRotationTitle',
		comment: 'errorRotationComment',
		camId: 1
	},
	notifyNoBackupCapacityActionStop: {
		id: 'noBackupCapacityActionStop',
		type: 'critical',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'noBackupCapacityActionStopTitle',
		comment: 'noBackupCapacityActionStopComment'
	},
	notifyNoBackupCapacityActionReduceCapacity: {
		id: 'noBackupCapacityActionReduceCapacity',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'noBackupCapacityActionReduceCapacityTitle',
		comment: 'noBackupCapacityActionReduceCapacityComment'
	},
	notifyVisualBackupNoStorageComment: {
		id: 'visualBackupNoStorageComment',
		type: 'warning',
		lastTriggered: 0,
		displayTimeSec: 10,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'notificationVisualBackupNoStorageTitle',
		comment: 'notificationVisualBackupNoStorageComment'
	},
	notifySuccessVisualBackupStart: {
		id: 'successVisualBackupStart',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'notificationSuccessVisualBackupStartTitle',
		comment: 'notificationSuccessVisualBackupStartComment'
	},
	notifySuccessVisualBackupStartUseCompleteSpace: {
		id: 'successVisualBackupStartUseCompleteSpace',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 0,
		miniTimeSec: 0,
		closeable: false,
		miniable: true,
		title: 'notificationSuccessVisualBackupStartUseCompleteSpaceTitle',
		comment: 'notificationSuccessVisualBackupStartUseCompleteSpaceComment'
	},
	notifyVisualBackupPaused: {
		id: 'visualBackupPaused',
		type: 'info',
		lastTriggered: 0,
		displayTimeSec: 20,
		miniTimeSec: 0,
		closeable: true,
		miniable: false,
		title: 'notificationVisualBackupPausedTitle',
		comment: 'notificationVisualBackupPausedComment'
	},
	apiToken: '1a2B3c4D5e6f7G8h',
	autoRotate0: true,
	autoRotate1: true,
	cameraSwitch: false,
	cam0Exists: true,
	cam1Exists: true,
	lineRateA: '2Gbps',
	lineRateB: '1Gbps',
	ver0: 'alStream1',
	ver1: 'alStream2',
	getConsentForm: '',
	rpm0: 4000,
	rpm1: 4000,
	RPM0: '4000',
	RPM1: '4000',
	dictRotation0: true,
	dictRotation1: true,
	downstat: 'idle',
	fpgaTemp: '60.3°C',
	exposure: true,
	whiteBalance: true,
	noiseSuppression: true,
	redGain: 0,
	blueGain: 0,
	brightness: 0,
	expo: 0,
	gain: 21,
	sharpness: 10,
	saturation: 0,
	contrast: 1.8,
	hdmiConnected: false,
	hdmiName: ' - ',
	hdmiSettings: 'FHD',
	cam0SelectedSensor: 0,
	cam1SelectedSensor: 0,
	cfg30: '60',
	cfg31: '30',
	cfg40: '30',
	cfg41: '0',
	language: 'English',
	licenseConfig: {
		'rotate-sensors': true,
		alignment: true,
		splitscreen: true,
		stream4K: true,
		'demo-logo': false
	},
	licenseModules: [
		{
			id: 'api',
			name: 'API',
			releaseVersion: '1.30',
			activationDate: '',
			activationCode: '',
			active: false,
			infoUrl: 'https://rotoclear.com/api-dokumentation-en.html',
			actionUrl: ''
		}
	],
	oct0: '70.1°C',
	oct1: '79.9°C',
	light0: false,
	light1: false,
	galleryInfo: {
		state: 'Off',
		refreshable: false,
		backupRefreshable: false,
		lastWriteTime: { seconds: 0, nanosecond: 0 }
	},
	hasInternet: true,
	macAddr: '00:15:5D:CE:57:26',
	hostname: 'rotoclear',
	netInfo: [
		{
			name: 'eth0',
			description: 'eth0',
			macAddress: '00:15:5D:CE:57:26',
			gateway: '',
			isServer: false,
			dhcp: true,
			dhcpServers: [],
			connections: [
				{ address: '192.168.113.10', netmask: '255.255.240.0', broadcast: '192.168.127.255' },
				{ address: 'fe80::215:5dff:fece:5726', netmask: '', broadcast: '' }
			],
			dhcpSelected: true,
			staticIp: '192.168.214.221',
			staticMask: '255.255.255.0',
			staticGateway: '192.168.214.1',
			staticDns: '8.8.8.8',
			staticUseGateway: false,
			staticUseDns: false
		}
	],
	pan0: { x: 50, y: 50 },
	pan1: { x: 50, y: 50 },
	pip: 0,
	recordingMode: 'inactive',
	recordingModeManualUsesBackupSettings: true,
	psi0: '1455mbar',
	psi1: '1008mbar',
	psiSetpoint: '1150mbar',
	changeVideoName: '',
	changeImageName: '',
	changePostName: '',
	changeBackupPostName: '',
	record: 'stop',
	recordingFilename: '',
	fotoFilename: '',
	recordTime: 0,
	rtspPort: 1025,
	rtspOn: false,
	rtspStatus: { status: 'off' },
	diskStorages: {
		simulator_usb: {
			fstype: 'noinfo',
			opts: 'noinfo',
			id: 'simulator_usb',
			name: 'USB-SIM',
			mountpoint: './simulator_usb',
			mountdevice: 'simulator_usb',
			canUse: true,
			canGalleryVideo: true,
			totalStr: '10TB',
			usedStr: '3.2TB',
			total: 10995116277760.0,
			used: 3518437208883.2,
			free: 7476679068876.8,
			percent: 32.0,
			backupRemainingVideoTime: '19d 3:05h',
			backupRemainingFrames: '49582199',
			backupRemainingVideoHours: 459,
			backupRemainingVideoSeconds: 1652739,
			recordingRemainingVideoTime: '19d 3:05h',
			recordingRemainingFrames: '49582199',
			recordingRemainingVideoHours: 459,
			recordingRemainingVideoSeconds: 1652739,
			isProcessing: false,
			isNet: false,
			readInfoTask: false,
			connectionLost: false,
			lastModified: { ticks: 0 },
			storeFileCount: 0,
			storeMediaCount: 0,
			diskUsageErrored: 0
		},
		'/mnt/wsl/docker-desktop-data/isocache': {
			fstype: 'ext4',
			opts: 'rw, relatime, discard, errors=remount-ro, data=ordered',
			id: '/mnt/wsl/docker-desktop-data/isocache',
			name: 'USB0',
			mountpoint: '/mnt/wsl/docker-desktop-data/isocache',
			mountdevice: 'isocache',
			canUse: true,
			canGalleryVideo: true,
			totalStr: '1006.854GB',
			usedStr: '39.04GB',
			total: 1081101176832.0,
			used: 41918730240.0,
			free: 984190091264.0,
			percent: 4.1,
			backupRemainingVideoTime: '2d 12:25h',
			backupRemainingFrames: '6526735',
			backupRemainingVideoHours: 60,
			backupRemainingVideoSeconds: 217557,
			recordingRemainingVideoTime: '2d 12:25h',
			recordingRemainingFrames: '6526735',
			recordingRemainingVideoHours: 60,
			recordingRemainingVideoSeconds: 217557,
			isProcessing: false,
			isNet: false,
			readInfoTask: false,
			connectionLost: false,
			lastModified: { ticks: 0 },
			storeFileCount: 0,
			storeMediaCount: 0,
			diskUsageErrored: 0
		},
		'/mnt/wsl/docker-desktop/docker-desktop-user-distro': {
			fstype: 'ext4',
			opts: 'rw, relatime, discard, errors=remount-ro, data=ordered',
			id: '/mnt/wsl/docker-desktop/docker-desktop-user-distro',
			name: 'USB1',
			mountpoint: '/mnt/wsl/docker-desktop/docker-desktop-user-distro',
			mountdevice: 'docker-desktop-user-distro',
			canUse: true,
			canGalleryVideo: true,
			totalStr: '1006.854GB',
			usedStr: '53.156MB',
			total: 1081101176832.0,
			used: 55738368.0,
			free: 1026053083136.0,
			percent: 0.0,
			backupRemainingVideoTime: '2d 15:00h',
			backupRemainingFrames: '6804353',
			backupRemainingVideoHours: 63,
			backupRemainingVideoSeconds: 226811,
			recordingRemainingVideoTime: '2d 15:00h',
			recordingRemainingFrames: '6804353',
			recordingRemainingVideoHours: 63,
			recordingRemainingVideoSeconds: 226811,
			isProcessing: false,
			isNet: false,
			readInfoTask: false,
			connectionLost: false,
			lastModified: { ticks: 0 },
			storeFileCount: 0,
			storeMediaCount: 0,
			diskUsageErrored: 0
		},
		'/mnt/wsl/docker-desktop/cli-tools': {
			fstype: 'iso9660',
			opts: 'ro, relatime, nojoliet, check=s, map=n, blocksize=2048, iocharset=iso8859-1',
			id: '/mnt/wsl/docker-desktop/cli-tools',
			name: 'USB2',
			mountpoint: '/mnt/wsl/docker-desktop/cli-tools',
			mountdevice: 'cli-tools',
			canUse: true,
			canGalleryVideo: true,
			totalStr: '458.348MB',
			usedStr: '458.348MB',
			total: 480612352.0,
			used: 480612352.0,
			free: 0.0,
			percent: 100.0,
			backupRemainingVideoTime: '0min',
			backupRemainingFrames: '0',
			backupRemainingVideoHours: 0,
			backupRemainingVideoSeconds: 0,
			recordingRemainingVideoTime: '0min',
			recordingRemainingFrames: '0',
			recordingRemainingVideoHours: 0,
			recordingRemainingVideoSeconds: 0,
			isProcessing: false,
			isNet: false,
			readInfoTask: false,
			connectionLost: false,
			lastModified: { ticks: 0 },
			storeFileCount: 0,
			storeMediaCount: 0,
			diskUsageErrored: 0
		}
	},
	updateDiskStorage: {
		fstype: 'noinfo',
		opts: 'noinfo',
		id: 'simulator_usb',
		name: 'USB-SIM',
		mountpoint: './simulator_usb',
		mountdevice: 'simulator_usb',
		canUse: true,
		canGalleryVideo: true,
		totalStr: '10TB',
		usedStr: '3.2TB',
		total: 10995116277760.0,
		used: 3518437208883.2,
		free: 7476679068876.8,
		percent: 32.0,
		backupRemainingVideoTime: '19d 3:05h',
		backupRemainingFrames: '49582199',
		backupRemainingVideoHours: 459,
		backupRemainingVideoSeconds: 1652739,
		recordingRemainingVideoTime: '19d 3:05h',
		recordingRemainingFrames: '49582199',
		recordingRemainingVideoHours: 459,
		recordingRemainingVideoSeconds: 1652739,
		isProcessing: false,
		isNet: false,
		readInfoTask: false,
		connectionLost: false,
		lastModified: { ticks: 0 },
		storeFileCount: 0,
		storeMediaCount: 0,
		diskUsageErrored: 0
	},
	editNetStorage: false,
	updateNetStorage: false,
	netStorages: {},
	recordingMountPoint: './simulator_usb',
	backupMountPoint: './simulator_usb',
	backupStorage: { id: 'simulator_usb', name: 'USB-SIM', kind: 'DiskStorage' },
	recordingStorage: { id: '', name: '', kind: 'NotSelected' },
	alignmentStream0: '0',
	alignmentStream1: '0',
	recordingResolution: 'HD',
	backupResolution: 'HD',
	recordingFps: 30,
	backupFps: 30,
	recordingPictureQuality: 80,
	backupPictureQuality: 80,
	mjpgStreamClientAllowed: true,
	mjpgStreamIsOpen: false,
	recordingWithTimeStamp: true,
	recordingWithDateStamp: true,
	logoRect: '',
	datetimeRect: '',
	systemDescription: {
		machineName: 'XPS-15-MARKUS',
		machineGuid: '',
		machineModel: '',
		machineManufacturer: '',
		osName: 'Ubuntu',
		osVersion: '22.04',
		cpuName: 'Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz',
		cpuManufacturer: 'GenuineIntel',
		cpuLogicalCount: 12,
		cpuPhysicalCount: 6,
		cpuMaxFrequencesGHz: 2.592008,
		cpuFeatures: [
			'fpu',
			'vme',
			'de',
			'pse',
			'tsc',
			'msr',
			'pae',
			'mce',
			'cx8',
			'apic',
			'sep',
			'mtrr',
			'pge',
			'mca',
			'cmov',
			'pat',
			'pse36',
			'clflush',
			'mmx',
			'fxsr',
			'sse',
			'sse2',
			'ss',
			'ht',
			'syscall',
			'nx',
			'pdpe1gb',
			'rdtscp',
			'lm',
			'constant_tsc',
			'arch_perfmon',
			'rep_good',
			'nopl',
			'xtopology',
			'cpuid',
			'pni',
			'pclmulqdq',
			'vmx',
			'ssse3',
			'fma',
			'cx16',
			'pdcm',
			'pcid',
			'sse4_1',
			'sse4_2',
			'x2apic',
			'movbe',
			'popcnt',
			'aes',
			'xsave',
			'avx',
			'f16c',
			'rdrand',
			'hypervisor',
			'lahf_lm',
			'abm',
			'3dnowprefetch',
			'invpcid_single',
			'ssbd',
			'ibrs',
			'ibpb',
			'stibp',
			'ibrs_enhanced',
			'tpr_shadow',
			'vnmi',
			'ept',
			'vpid',
			'ept_ad',
			'fsgsbase',
			'bmi1',
			'avx2',
			'smep',
			'bmi2',
			'erms',
			'invpcid',
			'rdseed',
			'adx',
			'smap',
			'clflushopt',
			'xsaveopt',
			'xsavec',
			'xgetbv1',
			'xsaves',
			'md_clear',
			'flush_l1d',
			'arch_capabilities'
		],
		gpuName: '',
		gpuDriverVersion: '',
		gpuMaxFPS: 0,
		pageSize: 4096
	},
	embeddedSystem: false,
	time: [2024, 3, 19, 11, 38, 13],
	timezone: 'Etc/UTC',
	ntpHost: 'pool.ntp.org',
	ntpStatus: { status: 'off', error: 'No Ntp Host.' },
	ntpSync: false,
	seconds: 1710848293,
	secondsUtc: 1710844693,
	timezones: [
		'Africa/Abidjan',
		'Africa/Accra',
		'Africa/Addis_Ababa',
		'Africa/Algiers',
		'Africa/Asmara',
		'Africa/Bamako',
		'Africa/Bangui',
		'Africa/Banjul',
		'Africa/Bissau',
		'Africa/Blantyre',
		'Africa/Brazzaville',
		'Africa/Bujumbura',
		'Africa/Cairo',
		'Africa/Casablanca',
		'Africa/Ceuta',
		'Africa/Conakry',
		'Africa/Dakar',
		'Africa/Dar_es_Salaam',
		'Africa/Djibouti',
		'Africa/Douala',
		'Africa/El_Aaiun',
		'Africa/Freetown',
		'Africa/Gaborone',
		'Africa/Harare',
		'Africa/Johannesburg',
		'Africa/Juba',
		'Africa/Kampala',
		'Africa/Khartoum',
		'Africa/Kigali',
		'Africa/Kinshasa',
		'Africa/Lagos',
		'Africa/Libreville',
		'Africa/Lome',
		'Africa/Luanda',
		'Africa/Lubumbashi',
		'Africa/Lusaka',
		'Africa/Malabo',
		'Africa/Maputo',
		'Africa/Maseru',
		'Africa/Mbabane',
		'Africa/Mogadishu',
		'Africa/Monrovia',
		'Africa/Nairobi',
		'Africa/Ndjamena',
		'Africa/Niamey',
		'Africa/Nouakchott',
		'Africa/Ouagadougou',
		'Africa/Porto-Novo',
		'Africa/Sao_Tome',
		'Africa/Timbuktu',
		'Africa/Tripoli',
		'Africa/Tunis',
		'Africa/Windhoek',
		'America/Adak',
		'America/Anchorage',
		'America/Anguilla',
		'America/Antigua',
		'America/Araguaina',
		'America/Argentina/Buenos_Aires',
		'America/Argentina/Catamarca',
		'America/Argentina/ComodRivadavia',
		'America/Argentina/Cordoba',
		'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja',
		'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos',
		'America/Argentina/Salta',
		'America/Argentina/San_Juan',
		'America/Argentina/San_Luis',
		'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia',
		'America/Aruba',
		'America/Asuncion',
		'America/Atikokan',
		'America/Atka',
		'America/Bahia',
		'America/Bahia_Banderas',
		'America/Barbados',
		'America/Belem',
		'America/Belize',
		'America/Blanc-Sablon',
		'America/Boa_Vista',
		'America/Bogota',
		'America/Boise',
		'America/Buenos_Aires',
		'America/Cambridge_Bay',
		'America/Campo_Grande',
		'America/Cancun',
		'America/Caracas',
		'America/Catamarca',
		'America/Cayenne',
		'America/Cayman',
		'America/Chicago',
		'America/Chihuahua',
		'America/Coral_Harbour',
		'America/Cordoba',
		'America/Costa_Rica',
		'America/Creston',
		'America/Cuiaba',
		'America/Curacao',
		'America/Danmarkshavn',
		'America/Dawson',
		'America/Dawson_Creek',
		'America/Denver',
		'America/Detroit',
		'America/Dominica',
		'America/Edmonton',
		'America/Eirunepe',
		'America/El_Salvador',
		'America/Ensenada',
		'America/Fort_Nelson',
		'America/Fort_Wayne',
		'America/Fortaleza',
		'America/Glace_Bay',
		'America/Godthab',
		'America/Goose_Bay',
		'America/Grand_Turk',
		'America/Grenada',
		'America/Guadeloupe',
		'America/Guatemala',
		'America/Guayaquil',
		'America/Guyana',
		'America/Halifax',
		'America/Havana',
		'America/Hermosillo',
		'America/Indiana/Indianapolis',
		'America/Indiana/Knox',
		'America/Indiana/Marengo',
		'America/Indiana/Petersburg',
		'America/Indiana/Tell_City',
		'America/Indiana/Vevay',
		'America/Indiana/Vincennes',
		'America/Indiana/Winamac',
		'America/Indianapolis',
		'America/Inuvik',
		'America/Iqaluit',
		'America/Jamaica',
		'America/Jujuy',
		'America/Juneau',
		'America/Kentucky/Louisville',
		'America/Kentucky/Monticello',
		'America/Knox_IN',
		'America/Kralendijk',
		'America/La_Paz',
		'America/Lima',
		'America/Los_Angeles',
		'America/Louisville',
		'America/Lower_Princes',
		'America/Maceio',
		'America/Managua',
		'America/Manaus',
		'America/Marigot',
		'America/Martinique',
		'America/Matamoros',
		'America/Mazatlan',
		'America/Mendoza',
		'America/Menominee',
		'America/Merida',
		'America/Metlakatla',
		'America/Mexico_City',
		'America/Miquelon',
		'America/Moncton',
		'America/Monterrey',
		'America/Montevideo',
		'America/Montreal',
		'America/Montserrat',
		'America/Nassau',
		'America/New_York',
		'America/Nipigon',
		'America/Nome',
		'America/Noronha',
		'America/North_Dakota/Beulah',
		'America/North_Dakota/Center',
		'America/North_Dakota/New_Salem',
		'America/Ojinaga',
		'America/Panama',
		'America/Pangnirtung',
		'America/Paramaribo',
		'America/Phoenix',
		'America/Port-au-Prince',
		'America/Port_of_Spain',
		'America/Porto_Acre',
		'America/Porto_Velho',
		'America/Puerto_Rico',
		'America/Punta_Arenas',
		'America/Rainy_River',
		'America/Rankin_Inlet',
		'America/Recife',
		'America/Regina',
		'America/Resolute',
		'America/Rio_Branco',
		'America/Rosario',
		'America/Santa_Isabel',
		'America/Santarem',
		'America/Santiago',
		'America/Santo_Domingo',
		'America/Sao_Paulo',
		'America/Scoresbysund',
		'America/Shiprock',
		'America/Sitka',
		'America/St_Barthelemy',
		'America/St_Johns',
		'America/St_Kitts',
		'America/St_Lucia',
		'America/St_Thomas',
		'America/St_Vincent',
		'America/Swift_Current',
		'America/Tegucigalpa',
		'America/Thule',
		'America/Thunder_Bay',
		'America/Tijuana',
		'America/Toronto',
		'America/Tortola',
		'America/Vancouver',
		'America/Virgin',
		'America/Whitehorse',
		'America/Winnipeg',
		'America/Yakutat',
		'America/Yellowknife',
		'Arctic/Longyearbyen',
		'Asia/Aden',
		'Asia/Almaty',
		'Asia/Amman',
		'Asia/Anadyr',
		'Asia/Aqtau',
		'Asia/Aqtobe',
		'Asia/Ashgabat',
		'Asia/Ashkhabad',
		'Asia/Atyrau',
		'Asia/Baghdad',
		'Asia/Bahrain',
		'Asia/Baku',
		'Asia/Bangkok',
		'Asia/Barnaul',
		'Asia/Beirut',
		'Asia/Bishkek',
		'Asia/Brunei',
		'Asia/Calcutta',
		'Asia/Chita',
		'Asia/Choibalsan',
		'Asia/Chongqing',
		'Asia/Chungking',
		'Asia/Colombo',
		'Asia/Dacca',
		'Asia/Damascus',
		'Asia/Dhaka',
		'Asia/Dili',
		'Asia/Dubai',
		'Asia/Dushanbe',
		'Asia/Famagusta',
		'Asia/Gaza',
		'Asia/Harbin',
		'Asia/Hebron',
		'Asia/Ho_Chi_Minh',
		'Asia/Hong_Kong',
		'Asia/Hovd',
		'Asia/Irkutsk',
		'Asia/Istanbul',
		'Asia/Jakarta',
		'Asia/Jayapura',
		'Asia/Jerusalem',
		'Asia/Kabul',
		'Asia/Kamchatka',
		'Asia/Karachi',
		'Asia/Kashgar',
		'Asia/Kathmandu',
		'Asia/Katmandu',
		'Asia/Khandyga',
		'Asia/Kolkata',
		'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur',
		'Asia/Kuching',
		'Asia/Kuwait',
		'Asia/Macao',
		'Asia/Macau',
		'Asia/Magadan',
		'Asia/Makassar',
		'Asia/Manila',
		'Asia/Muscat',
		'Asia/Nicosia',
		'Asia/Novokuznetsk',
		'Asia/Novosibirsk',
		'Asia/Omsk',
		'Asia/Oral',
		'Asia/Phnom_Penh',
		'Asia/Pontianak',
		'Asia/Pyongyang',
		'Asia/Qatar',
		'Asia/Qyzylorda',
		'Asia/Rangoon',
		'Asia/Riyadh',
		'Asia/Saigon',
		'Asia/Sakhalin',
		'Asia/Samarkand',
		'Asia/Seoul',
		'Asia/Shanghai',
		'Asia/Singapore',
		'Asia/Srednekolymsk',
		'Asia/Taipei',
		'Asia/Tashkent',
		'Asia/Tbilisi',
		'Asia/Tehran',
		'Asia/Tel_Aviv',
		'Asia/Thimbu',
		'Asia/Thimphu',
		'Asia/Tokyo',
		'Asia/Tomsk',
		'Asia/Ujung_Pandang',
		'Asia/Ulaanbaatar',
		'Asia/Ulan_Bator',
		'Asia/Urumqi',
		'Asia/Ust-Nera',
		'Asia/Vientiane',
		'Asia/Vladivostok',
		'Asia/Yakutsk',
		'Asia/Yangon',
		'Asia/Yekaterinburg',
		'Asia/Yerevan',
		'Australia/ACT',
		'Australia/Adelaide',
		'Australia/Brisbane',
		'Australia/Broken_Hill',
		'Australia/Canberra',
		'Australia/Currie',
		'Australia/Darwin',
		'Australia/Eucla',
		'Australia/Hobart',
		'Australia/LHI',
		'Australia/Lindeman',
		'Australia/Lord_Howe',
		'Australia/Melbourne',
		'Australia/NSW',
		'Australia/North',
		'Australia/Perth',
		'Australia/Queensland',
		'Australia/South',
		'Australia/Sydney',
		'Australia/Tasmania',
		'Australia/Victoria',
		'Australia/West',
		'Australia/Yancowinna',
		'Brazil/Acre',
		'Brazil/DeNoronha',
		'Brazil/East',
		'Brazil/West',
		'CET',
		'CST6CDT',
		'Canada/Atlantic',
		'Canada/Central',
		'Canada/Eastern',
		'Canada/Mountain',
		'Canada/Newfoundland',
		'Canada/Pacific',
		'Canada/Saskatchewan',
		'Canada/Yukon',
		'Chile/Continental',
		'Chile/EasterIsland',
		'Cuba',
		'EET',
		'EST',
		'EST5EDT',
		'Egypt',
		'Eire',
		'Etc/GMT',
		'Etc/GMT+0',
		'Etc/GMT+1',
		'Etc/GMT+10',
		'Etc/GMT+11',
		'Etc/GMT+12',
		'Etc/GMT+2',
		'Etc/GMT+3',
		'Etc/GMT+4',
		'Etc/GMT+5',
		'Etc/GMT+6',
		'Etc/GMT+7',
		'Etc/GMT+8',
		'Etc/GMT+9',
		'Etc/GMT-0',
		'Etc/GMT-1',
		'Etc/GMT-10',
		'Etc/GMT-11',
		'Etc/GMT-12',
		'Etc/GMT-13',
		'Etc/GMT-14',
		'Etc/GMT-2',
		'Etc/GMT-3',
		'Etc/GMT-4',
		'Etc/GMT-5',
		'Etc/GMT-6',
		'Etc/GMT-7',
		'Etc/GMT-8',
		'Etc/GMT-9',
		'Etc/GMT0',
		'Etc/Greenwich',
		'Etc/UCT',
		'Etc/UTC',
		'Etc/Universal',
		'Etc/Zulu',
		'Europe/Amsterdam',
		'Europe/Andorra',
		'Europe/Astrakhan',
		'Europe/Athens',
		'Europe/Belfast',
		'Europe/Belgrade',
		'Europe/Berlin',
		'Europe/Bratislava',
		'Europe/Brussels',
		'Europe/Bucharest',
		'Europe/Budapest',
		'Europe/Busingen',
		'Europe/Chisinau',
		'Europe/Copenhagen',
		'Europe/Dublin',
		'Europe/Gibraltar',
		'Europe/Guernsey',
		'Europe/Helsinki',
		'Europe/Isle_of_Man',
		'Europe/Istanbul',
		'Europe/Jersey',
		'Europe/Kaliningrad',
		'Europe/Kiev',
		'Europe/Kirov',
		'Europe/Lisbon',
		'Europe/Ljubljana',
		'Europe/London',
		'Europe/Luxembourg',
		'Europe/Madrid',
		'Europe/Malta',
		'Europe/Mariehamn',
		'Europe/Minsk',
		'Europe/Monaco',
		'Europe/Moscow',
		'Europe/Nicosia',
		'Europe/Oslo',
		'Europe/Paris',
		'Europe/Podgorica',
		'Europe/Prague',
		'Europe/Riga',
		'Europe/Rome',
		'Europe/Samara',
		'Europe/San_Marino',
		'Europe/Sarajevo',
		'Europe/Saratov',
		'Europe/Simferopol',
		'Europe/Skopje',
		'Europe/Sofia',
		'Europe/Stockholm',
		'Europe/Tallinn',
		'Europe/Tirane',
		'Europe/Tiraspol',
		'Europe/Ulyanovsk',
		'Europe/Uzhgorod',
		'Europe/Vaduz',
		'Europe/Vatican',
		'Europe/Vienna',
		'Europe/Vilnius',
		'Europe/Volgograd',
		'Europe/Warsaw',
		'Europe/Zagreb',
		'Europe/Zaporozhye',
		'Europe/Zurich',
		'GB',
		'GB-Eire',
		'GMT',
		'GMT+0',
		'GMT-0',
		'GMT0',
		'Greenwich',
		'HST',
		'Hongkong',
		'Iceland',
		'Indian/Antananarivo',
		'Indian/Chagos',
		'Indian/Christmas',
		'Indian/Cocos',
		'Indian/Comoro',
		'Indian/Kerguelen',
		'Indian/Mahe',
		'Indian/Maldives',
		'Indian/Mauritius',
		'Indian/Mayotte',
		'Indian/Reunion',
		'Iran',
		'Israel',
		'Jamaica',
		'Japan',
		'Kwajalein',
		'Libya',
		'MET',
		'MST',
		'MST7MDT',
		'Mexico/BajaNorte',
		'Mexico/BajaSur',
		'Mexico/General',
		'NZ',
		'NZ-CHAT',
		'Navajo',
		'PRC',
		'PST8PDT',
		'Pacific/Apia',
		'Pacific/Auckland',
		'Pacific/Bougainville',
		'Pacific/Chatham',
		'Pacific/Chuuk',
		'Pacific/Easter',
		'Pacific/Efate',
		'Pacific/Enderbury',
		'Pacific/Fakaofo',
		'Pacific/Fiji',
		'Pacific/Funafuti',
		'Pacific/Galapagos',
		'Pacific/Gambier',
		'Pacific/Guadalcanal',
		'Pacific/Guam',
		'Pacific/Honolulu',
		'Pacific/Johnston',
		'Pacific/Kiritimati',
		'Pacific/Kosrae',
		'Pacific/Kwajalein',
		'Pacific/Majuro',
		'Pacific/Marquesas',
		'Pacific/Midway',
		'Pacific/Nauru',
		'Pacific/Niue',
		'Pacific/Norfolk',
		'Pacific/Noumea',
		'Pacific/Pago_Pago',
		'Pacific/Palau',
		'Pacific/Pitcairn',
		'Pacific/Pohnpei',
		'Pacific/Ponape',
		'Pacific/Port_Moresby',
		'Pacific/Rarotonga',
		'Pacific/Saipan',
		'Pacific/Samoa',
		'Pacific/Tahiti',
		'Pacific/Tarawa',
		'Pacific/Tongatapu',
		'Pacific/Truk',
		'Pacific/Wake',
		'Pacific/Wallis',
		'Pacific/Yap',
		'Poland',
		'Portugal',
		'ROC',
		'ROK',
		'Singapore',
		'Turkey',
		'UCT',
		'US/Alaska',
		'US/Aleutian',
		'US/Arizona',
		'US/Central',
		'US/East-Indiana',
		'US/Eastern',
		'US/Hawaii',
		'US/Indiana-Starke',
		'US/Michigan',
		'US/Mountain',
		'US/Pacific',
		'US/Samoa',
		'UTC',
		'Universal',
		'W-SU',
		'WET',
		'Zulu'
	],
	firmwarePaths: [],
	configPaths: [],
	onlineFirmwareUpdate: {},
	onlineSoftwareConfig: {},
	onlineFirmwareDownloadProgress: -1.0,
	syncOnlineUpdate: false,
	localInstallFirmwareTimer: '',
	connectionUrls: {
		mjpegHttp: [],
		mjpegHttps: [],
		http: ['http://192.168.113.10:3000'],
		https: [],
		rtsp: []
	},
	users: {
		admin: {
			username: 'admin',
			permissions: {
				isAdmin: true,
				table: {
					recordingFilename: ['r'],
					light1: ['r', 'w'],
					pan1: ['r', 'w'],
					currentClients: ['a'],
					notifyErrorJpgstoreIo: ['r'],
					fotoFilename: ['r'],
					httpPort: ['r', 'w'],
					backupResolution: ['r', 'w'],
					notifyErrorStoreSpeed: ['r'],
					rpm1: ['r', 'w'],
					localFirmwareAction: ['a'],
					getBackupFileList: ['a'],
					userLogout: ['a'],
					psi1: ['r'],
					hdmiConnected: ['r'],
					netSettings: [],
					datetimeRect: ['r', 'w'],
					rcbasicVersion: ['r'],
					sharpness: ['r', 'w'],
					certPassPhrase: ['n'],
					notifyRecBackupNoSettings: ['r'],
					netInfo: ['r'],
					startLocalFirmwareUpdate: ['a'],
					rpm0: ['r', 'w'],
					embeddedSystem: ['r'],
					timezone: ['r', 'w'],
					hasInternet: ['r'],
					recordingPictureQuality: ['r', 'w'],
					fpgaTemp: ['r'],
					notifyVisualBackupNoStorageComment: ['r'],
					notifyRecNoSettings: ['r'],
					userLogin: ['a'],
					light0: ['r', 'w'],
					ntpSync: ['r', 'w'],
					backupFileCapacity: ['r'],
					notifyErrorRotation0: ['r'],
					expo: ['r', 'w'],
					alignmentStream1: ['r', 'w'],
					notifyRecError: ['r'],
					cam0SelectedSensor: ['r', 'w'],
					whiteBalance: ['r', 'w'],
					recordingModeManualUsesBackupSettings: ['r', 'w'],
					notifyErrorNewpathPath: ['r'],
					activateLicenseModule: ['a'],
					syncOnlineUpdate: ['r', 'w'],
					notifyOnlineFirmwareUpdate: ['r'],
					exposure: ['r', 'w'],
					changeUserPassword: ['a'],
					mediaList: ['a'],
					dictRotation1: ['r', 'w'],
					changePostName: ['r', 'w'],
					oneWebserverIsAlwaysRunning: ['r'],
					cfg30: ['r'],
					diskStorages: ['r'],
					autoRotate1: ['r', 'w'],
					backupPictureQuality: ['r', 'w'],
					changeImageName: ['r', 'w'],
					localInstallFirmwareTimer: ['r'],
					ntpStatus: ['r'],
					getClientSettings: ['a'],
					secondsUtc: ['r'],
					brightness: ['r', 'w'],
					notifyWarningRotation1: ['r'],
					macAddr: ['r'],
					alignmentStream0: ['r', 'w'],
					ntpHost: ['r', 'w'],
					notifyNewerLocalFirmwareUpdate: ['r'],
					seconds: ['r'],
					notifyOnlineSoftwareConfig: ['r'],
					oct0: ['r'],
					notifyPressureToHigh1: ['r'],
					restart: ['a'],
					netStoragePasswords: [],
					zoom0: ['r', 'w'],
					notifyStorageDetected: ['r'],
					hdmiName: ['r'],
					RPM0: ['r'],
					getBackupInfo: ['a'],
					notifyDictRotation1: ['r'],
					connectionUrls: ['r'],
					systemDescription: ['r'],
					notifySuccessVisualBackupStartUseCompleteSpace: ['r'],
					blueGain: ['r', 'w'],
					onlineFirmwareDownloadProgress: ['r'],
					createTag: ['a'],
					recordingFps: ['r', 'w'],
					notifyErrorJpgstoreDiskspace: ['r'],
					ver0: ['r'],
					notifyCifsConnectionError: ['r'],
					cfg40: ['r'],
					onlineInstallConfigTimestamp: [],
					cameraSwitch: ['r', 'w'],
					swVersionNumber: ['r'],
					backupMountPoint: ['r'],
					reset: ['a'],
					notifyErrorStoreaviDrop: ['r'],
					notifyVisualBackupPaused: ['r'],
					timezones: ['r'],
					httpOn: ['r', 'w'],
					cam1Exists: ['r'],
					hostname: ['r', 'w'],
					autoRotate0: ['r', 'w'],
					rtspPort: ['r', 'w'],
					notifyNoBackupCapacityActionStop: ['r'],
					notifyErrorStoreaviRelease: ['r'],
					notifyWarningDiskmonFreespace: ['r'],
					updateHttpsCertificate: ['r', 'w'],
					cfg41: ['r'],
					updateDiskStorage: ['r'],
					storageBackupCapacity: ['r'],
					changeVideoName: ['r', 'w'],
					notifyWarningNoServerRunning: ['r'],
					createHttpsCertificate: ['a'],
					apiToken: ['r', 'w'],
					record: ['r', 'w'],
					zoomTo1: ['w'],
					httpsPort: ['r', 'w'],
					notifyNewerLocalFirmwareUpdateWithTimer: ['r'],
					notifyPressureToHigh0: ['r'],
					downstat: ['r'],
					notifySuccessVisualBackupStart: ['r'],
					recordingResolution: ['r', 'w'],
					logoRect: ['r', 'w'],
					updateNetStorage: ['r'],
					lastSavedBackupStorage: ['n'],
					firmwarePaths: ['r'],
					editNetStorage: ['r', 'a'],
					users: ['r', 'w'],
					lineRateB: ['r'],
					notifyPressureToLow0: ['r'],
					notifyNoBackupCapacity: ['r'],
					noiseSuppression: ['r', 'w'],
					ver1: ['r'],
					rtspStatus: ['r'],
					notifyWarningPortUsed: ['r'],
					removeNetStorage: ['a'],
					recordingMode: ['r'],
					mediaDelete: ['a'],
					oct1: ['r'],
					onlineFirmwareUpdate: ['r'],
					getConsentForm: ['r'],
					httpsCertificate: ['r'],
					pan0: ['r', 'w'],
					notifyErrorSnapPath: ['r'],
					lineRateA: ['r'],
					cam1SelectedSensor: ['r', 'w'],
					configPaths: ['r'],
					psiSetpoint: ['r'],
					updateNetDevice: ['w'],
					licenseModules: ['r'],
					notifyWarningRotation0: ['r'],
					hdmiSettings: ['r'],
					mjpgStreamIsOpen: ['r', 'w'],
					initialized: ['r', 'w'],
					language: ['r', 'w'],
					contrast: ['r', 'w'],
					userAuthentication: ['r', 'w'],
					swVersion: ['r'],
					mjpgStreamClientAllowed: ['r', 'w'],
					notifyPressureToLow1: ['r'],
					recordingStorage: ['r', 'w'],
					updateTag: ['a'],
					backupOnReachingRecordingTimeCapacityAction: ['r', 'w'],
					notifyDictRotation0: ['r'],
					startLocalConfigUpdate: ['a'],
					backupStorage: ['r', 'w'],
					cfg31: ['r'],
					galleryInfo: ['r'],
					backupUseCompleteSpace: ['r', 'w'],
					recordingWithTimeStamp: ['r', 'w'],
					saturation: ['r', 'w'],
					notifyNoBackupCapacityActionReduceCapacity: ['r'],
					httpsOn: ['r', 'w'],
					changeBackupPostName: ['r', 'w'],
					fmVersion: ['r'],
					mediaDownload: ['a'],
					notifyErrorRotation1: ['r'],
					cam0Exists: ['r'],
					dictRotation0: ['r', 'w'],
					recordingWithDateStamp: ['r', 'w'],
					time: ['r', 'w'],
					psi0: ['r'],
					backupRemainingCapacity: ['r'],
					systemReboot: ['a'],
					zoom1: ['r', 'w'],
					notifyErrorStopFinalizeFAILED: ['r'],
					deleteTags: ['a'],
					backupActive: ['r', 'w'],
					httpStatus: ['r'],
					recordTime: ['r'],
					RPM1: ['r'],
					onlineSoftwareConfig: ['r'],
					lastSavedRecordingStorage: ['n'],
					pip: ['r', 'w'],
					rtspOn: ['r', 'w'],
					netStorages: ['r'],
					notifyErrorInvalidCertificate: ['r'],
					addNetStorage: ['a'],
					localInstallFirmwareName: ['n'],
					getTags: ['a'],
					startOnlineFirmwareUpdate: ['a'],
					recordingMountPoint: ['r'],
					notifyErrorJpgnetstoreIo: ['r'],
					licenseConfig: ['r'],
					zoomTo0: ['w'],
					backupRemainingCapacitySeconds: ['r'],
					notifyErrorStartInitFAILED: ['r'],
					notifyWarningNetworkUniqueIP: ['r'],
					backupFps: ['r', 'w'],
					notifyErrorJpgstoreSpeed: ['r'],
					redGain: ['r', 'w'],
					backupStoredFileDuration: ['r'],
					startOnlineConfigUpdate: ['a'],
					gain: ['r', 'w'],
					takePicture: ['a'],
					userPasswords: [],
					systemPerformance: ['a'],
					backupNumberOfSavedHours: ['r', 'w'],
					httpsStatus: ['r'],
					backupRemainingCapacityHours: ['r']
				}
			},
			loggedIn: false,
			lastLoggedIn: ''
		},
		'API-User': {
			username: 'API-User',
			permissions: {
				isAdmin: false,
				table: {
					recordingFilename: ['r'],
					light1: ['r', 'w'],
					pan1: ['r', 'w'],
					currentClients: ['a'],
					notifyErrorJpgstoreIo: ['r'],
					fotoFilename: ['r'],
					httpPort: ['r', 'w'],
					backupResolution: ['r', 'w'],
					notifyErrorStoreSpeed: ['r'],
					rpm1: ['r', 'w'],
					localFirmwareAction: ['a'],
					getBackupFileList: ['a'],
					userLogout: ['a'],
					psi1: ['r'],
					hdmiConnected: ['r'],
					netSettings: [],
					datetimeRect: ['r', 'w'],
					rcbasicVersion: ['r'],
					sharpness: ['r', 'w'],
					certPassPhrase: ['n'],
					notifyRecBackupNoSettings: ['r'],
					netInfo: ['r'],
					startLocalFirmwareUpdate: ['a'],
					rpm0: ['r', 'w'],
					embeddedSystem: ['r'],
					timezone: ['r', 'w'],
					hasInternet: ['r'],
					recordingPictureQuality: ['r', 'w'],
					fpgaTemp: ['r'],
					notifyVisualBackupNoStorageComment: ['r'],
					notifyRecNoSettings: ['r'],
					userLogin: ['a'],
					light0: ['r', 'w'],
					ntpSync: ['r', 'w'],
					backupFileCapacity: ['r'],
					notifyErrorRotation0: ['r'],
					expo: ['r', 'w'],
					alignmentStream1: ['r', 'w'],
					notifyRecError: ['r'],
					cam0SelectedSensor: ['r', 'w'],
					whiteBalance: ['r', 'w'],
					recordingModeManualUsesBackupSettings: ['r', 'w'],
					notifyErrorNewpathPath: ['r'],
					activateLicenseModule: ['a'],
					syncOnlineUpdate: ['r', 'w'],
					notifyOnlineFirmwareUpdate: ['r'],
					exposure: ['r', 'w'],
					changeUserPassword: ['a'],
					mediaList: ['a'],
					dictRotation1: ['r', 'w'],
					changePostName: ['r', 'w'],
					oneWebserverIsAlwaysRunning: ['r'],
					cfg30: ['r'],
					diskStorages: ['r'],
					autoRotate1: ['r', 'w'],
					backupPictureQuality: ['r', 'w'],
					changeImageName: ['r', 'w'],
					localInstallFirmwareTimer: ['r'],
					ntpStatus: ['r'],
					getClientSettings: ['a'],
					secondsUtc: ['r'],
					brightness: ['r', 'w'],
					notifyWarningRotation1: ['r'],
					macAddr: ['r'],
					alignmentStream0: ['r', 'w'],
					ntpHost: ['r', 'w'],
					notifyNewerLocalFirmwareUpdate: ['r'],
					seconds: ['r'],
					notifyOnlineSoftwareConfig: ['r'],
					oct0: ['r'],
					notifyPressureToHigh1: ['r'],
					restart: ['a'],
					netStoragePasswords: [],
					zoom0: ['r', 'w'],
					notifyStorageDetected: ['r'],
					hdmiName: ['r'],
					RPM0: ['r'],
					getBackupInfo: ['a'],
					notifyDictRotation1: ['r'],
					connectionUrls: ['r'],
					systemDescription: ['r'],
					notifySuccessVisualBackupStartUseCompleteSpace: ['r'],
					blueGain: ['r', 'w'],
					onlineFirmwareDownloadProgress: ['r'],
					createTag: ['a'],
					recordingFps: ['r', 'w'],
					notifyErrorJpgstoreDiskspace: ['r'],
					ver0: ['r'],
					notifyCifsConnectionError: ['r'],
					cfg40: ['r'],
					onlineInstallConfigTimestamp: [],
					cameraSwitch: ['r', 'w'],
					swVersionNumber: ['r'],
					backupMountPoint: ['r'],
					reset: ['a'],
					notifyErrorStoreaviDrop: ['r'],
					notifyVisualBackupPaused: ['r'],
					timezones: ['n'],
					httpOn: ['r', 'w'],
					cam1Exists: ['r'],
					hostname: ['r', 'w'],
					autoRotate0: ['r', 'w'],
					rtspPort: ['r', 'w'],
					notifyNoBackupCapacityActionStop: ['r'],
					notifyErrorStoreaviRelease: ['r'],
					notifyWarningDiskmonFreespace: ['r'],
					updateHttpsCertificate: ['r', 'w'],
					cfg41: ['r'],
					updateDiskStorage: ['r'],
					storageBackupCapacity: ['r'],
					changeVideoName: ['r', 'w'],
					notifyWarningNoServerRunning: ['r'],
					createHttpsCertificate: ['a'],
					apiToken: ['n'],
					record: ['r', 'w'],
					zoomTo1: ['w'],
					httpsPort: ['r', 'w'],
					notifyNewerLocalFirmwareUpdateWithTimer: ['r'],
					notifyPressureToHigh0: ['r'],
					downstat: ['r'],
					notifySuccessVisualBackupStart: ['r'],
					recordingResolution: ['r', 'w'],
					logoRect: ['r', 'w'],
					updateNetStorage: ['r'],
					lastSavedBackupStorage: ['n'],
					firmwarePaths: ['r'],
					editNetStorage: ['r', 'a'],
					users: ['n'],
					lineRateB: ['r'],
					notifyPressureToLow0: ['r'],
					notifyNoBackupCapacity: ['r'],
					noiseSuppression: ['r', 'w'],
					ver1: ['r'],
					rtspStatus: ['r'],
					notifyWarningPortUsed: ['r'],
					removeNetStorage: ['a'],
					recordingMode: ['r'],
					mediaDelete: ['a'],
					oct1: ['r'],
					onlineFirmwareUpdate: ['r'],
					getConsentForm: ['n'],
					httpsCertificate: ['r'],
					pan0: ['r', 'w'],
					notifyErrorSnapPath: ['r'],
					lineRateA: ['r'],
					cam1SelectedSensor: ['r', 'w'],
					configPaths: ['r'],
					psiSetpoint: ['r'],
					updateNetDevice: ['w'],
					licenseModules: ['r'],
					notifyWarningRotation0: ['r'],
					hdmiSettings: ['r'],
					mjpgStreamIsOpen: ['r', 'w'],
					initialized: ['r', 'w'],
					language: ['r', 'w'],
					contrast: ['r', 'w'],
					userAuthentication: ['r', 'w'],
					swVersion: ['r'],
					mjpgStreamClientAllowed: ['r', 'w'],
					notifyPressureToLow1: ['r'],
					recordingStorage: ['r', 'w'],
					updateTag: ['a'],
					backupOnReachingRecordingTimeCapacityAction: ['r', 'w'],
					notifyDictRotation0: ['r'],
					startLocalConfigUpdate: ['a'],
					backupStorage: ['r', 'w'],
					cfg31: ['r'],
					galleryInfo: ['r'],
					backupUseCompleteSpace: ['r', 'w'],
					recordingWithTimeStamp: ['r', 'w'],
					saturation: ['r', 'w'],
					notifyNoBackupCapacityActionReduceCapacity: ['r'],
					httpsOn: ['r', 'w'],
					changeBackupPostName: ['r', 'w'],
					fmVersion: ['r'],
					mediaDownload: ['a'],
					notifyErrorRotation1: ['r'],
					cam0Exists: ['r'],
					dictRotation0: ['r', 'w'],
					recordingWithDateStamp: ['r', 'w'],
					time: ['r', 'w'],
					psi0: ['r'],
					backupRemainingCapacity: ['r'],
					systemReboot: ['a'],
					zoom1: ['r', 'w'],
					notifyErrorStopFinalizeFAILED: ['r'],
					deleteTags: ['a'],
					backupActive: ['r', 'w'],
					httpStatus: ['r'],
					recordTime: ['r'],
					RPM1: ['r'],
					onlineSoftwareConfig: ['r'],
					lastSavedRecordingStorage: ['n'],
					pip: ['r', 'w'],
					rtspOn: ['r', 'w'],
					netStorages: ['r'],
					notifyErrorInvalidCertificate: ['r'],
					addNetStorage: ['a'],
					localInstallFirmwareName: ['n'],
					getTags: ['a'],
					startOnlineFirmwareUpdate: ['a'],
					recordingMountPoint: ['r'],
					notifyErrorJpgnetstoreIo: ['r'],
					licenseConfig: ['r'],
					zoomTo0: ['w'],
					backupRemainingCapacitySeconds: ['r'],
					notifyErrorStartInitFAILED: ['r'],
					notifyWarningNetworkUniqueIP: ['r'],
					backupFps: ['r', 'w'],
					notifyErrorJpgstoreSpeed: ['r'],
					redGain: ['r', 'w'],
					backupStoredFileDuration: ['r'],
					startOnlineConfigUpdate: ['a'],
					gain: ['r', 'w'],
					takePicture: ['a'],
					userPasswords: [],
					systemPerformance: ['a'],
					backupNumberOfSavedHours: ['r', 'w'],
					httpsStatus: ['r'],
					backupRemainingCapacityHours: ['r']
				}
			},
			loggedIn: false,
			lastLoggedIn: ''
		}
	},
	userAuthentication: { on: false },
	zoom0: 0,
	zoom1: 0,
	swVersion: 'RC V2.9.28',
	fmVersion: 'Cortona Simulator v0.0.1',
	swVersionNumber: '2.9.28',
	rcbasicVersion: 'V1.1.0',
	initialized: true,
	storageBackupCapacity: '19d 3h',
	backupRemainingCapacity: '19d 3:05h',
	backupRemainingCapacityHours: 459,
	backupRemainingCapacitySeconds: 1652739,
	backupFileCapacity: '0 nanoseconds',
	backupStoredFileDuration: '0 nanoseconds',
	backupUseCompleteSpace: false,
	backupNumberOfSavedHours: 12,
	backupOnReachingRecordingTimeCapacityAction: 'reduceMaxTime',
	backupActive: false,
	oneWebserverIsAlwaysRunning: true,
	httpPort: 3000,
	httpOn: true,
	httpStatus: { status: 'on', address: '192.168.113.10', port: 3000, error: '' },
	httpsPort: 443,
	httpsOn: true,
	updateHttpsCertificate: '',
	httpsStatus: { status: 'error', address: '', port: 443, error: 'Permission denied' },
	httpsCertificate: {
		subject: {
			countryName: 'EU',
			stateOrProvinceName: 'Germany',
			locality: 'Heidelberg',
			organization: 'Rotoclear',
			organizationalUnit: '',
			commonName: 'rotoclear.local'
		},
		issuer: {
			countryName: 'DE',
			stateOrProvinceName: '',
			locality: 'Heidelberg',
			organization: 'Rotoclear GmbH',
			organizationalUnit: '',
			commonName: 'www.rotoclear.com'
		},
		subjectAlternatives: [
			{ kind: 'DNS', name: 'rotoclear.local' },
			{ kind: 'DNS', name: 'rotoclear.fritz.box' }
		],
		notBefore: '2024-12-12T16:57:01Z',
		notAfter: '2034-12-12T16:57:01Z',
		domains: ['rotoclear.local', 'rotoclear.fritz.box'],
		subjectDescription: '/C=EU/ST=Germany/L=Heidelberg/O=Rotoclear/CN=rotoclear.local',
		issuerDescription: '/C=DE/L=Heidelberg/O=Rotoclear GmbH/CN=www.rotoclear.com'
	}
};

export default state;
